### ISSUE TITLE
请问怎么运行呢？

### ISSUE THREAD

**Issue by BugMaker2002** [Ragnap/NEU_File_System#1]
我在VSCODE当中打开该项目，按F5运行main.cpp，但是没有弹出控制台
![image](https://github.com/Ragnap/NEU_File_System/assets/110211332/13cee5f1-90eb-4da6-9cc0-2f6744d1df8a)

**Comment by Ragnap** [comment]
额不是很能懂您的意思，这个项目的确是只需要编译运行`main.cpp`即可，有关的函数定义与实现在了`/src`下的各个头文件中。测试了一下是能够运行的，时间比较赶没有补完README造成的麻烦还请谅解。
如果您是想让vscode运行cpp程序时弹出独立的控制台，可能需要调整vscode设置，将 `launch.json` 中的 `"externalConsole"` 字段的值设置为 `true`，其他的配置您可以去搜索一下有关在vscode中配置cpp运行配置的文章，或者参考[微软官方的帖子](https://code.visualstudio.com/docs/cpp/config-mingw)。

**Comment by BugMaker2002** [comment]
好的，谢谢您！我发现可以直接在cmd里面运行main.exe文件，这样也是可以的对吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ragnap/NEU_File_System"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月29日(星期五) 中午12:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ragnap/NEU_File_System] 请问怎么运行呢？ (Issue #1)





 
额不是很能懂您的意思，这个项目的确是只需要编译运行main.cpp即可，有关的函数定义与实现在了/src下的各个头文件中。测试了一下是能够运行的，时间比较赶没有补完README造成的麻烦还请谅解。
 如果您是想让vscode运行cpp程序时弹出独立的控制台，可能需要调整vscode设置，将 launch.json 中的 "externalConsole" 字段的值设置为 true，其他的配置您可以去搜索一下有关在vscode中配置cpp运行配置的文章，或者参考微软官方的帖子。
